"""init

Revision ID: b1c0413eb286
Revises: 
Create Date: 2024-10-07 02:14:49.097142

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1c0413eb286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('position_timehours_idx', table_name='position', postgresql_using='gist')
    op.drop_table('position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('vesselid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timehours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('z', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('vesselid', 'timehours', name='position_pkey')
    )
    op.create_index('position_timehours_idx', 'position', ['timehours'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
